// Create package repositories here ...

// Import the required packages here ...

// Declare ProductRepository interface here ...

// Create RepositoryProduct function here ... 

// Create FindProducts method here ...

// Create GetProduct method here ...

// Create CreateProduct method here ...