package jwtToken

// Import fmt and jwt here ...

// Create SecretKey as Global Variable here ...

// Create GenerateToken function here ...

// Create VerifyToken function here ...

// Create DecodeToken function here ...