// Create package handlers here ...

// Import the required packages here ...

// Declare handlerProduct  struct here ...

// HandlerProduct function here ... 

// Create FindProducts method here ...

// Create GetProduct method here ...

// Create CreateProduct method here ...

// Create convertResponseProduct function here ...