// Create package handlers here ...

// Import the required packages here ...

// Declare handlerProfile struct here ...

// HandlerProfile function here ... 

// Create GetProfile method here ...

// Create convertResponseProfile function here ...